Zl\IntegrationBundle\Entity\User:
  type: entity
  table: user 
  id:
      id:
        type: integer
        generator: { strategy: AUTO }
  fields:
      login:
        type: string
        length: 100
      password:
        type: string
        length: 100
