parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: zl
    database_user: zl
    database_password: madeinchina
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 2c2af60ad33b3cc4217e10b1b91cd0d5b
    database_path: null
