parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: integration
    database_user: root
    database_password: madeinchina
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: fb92dc932554725d46617e69ecade1c296926874
    database_path: null
